branch-defaults:
  aws:
    environment: null
    group_suffix: null
global:
  application_name: SnowballDjango
  branch: aws
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: admin-092395709117
  repository: SnowballDjango
  sc: git
  workspace_type: Application
